# A crash course on `numpy` - Part II (Linear Algebra)

Saleh Rezaeiravesh, saleh.rezaeiravesh@manchester.ac.uk <br>
Department of Fluids and Environment, The University of Manchester, Manchester, UK
___

In this notebook, we cover the basics of the linear algebra offered by `numpy`. The selection of the topics is based on the needs in the Numerical Methods & Computing unit. Please refer to [the official page of `numpy.linalg`](https://numpy.org/devdocs/reference/routines.linalg.html) for more instructions and examples. 

### Intended Learning Outcomes:
By reading and running this notebook, the students should be able to:
* Import the `numpy` subclass `linalg` and its methods. 
* Use `numpy.linalg` for applying basic linear algebra techniques relevant to the Numerical Methods & Computing unit. 

## 1. Import the library
We need to import `numpy` in order to be able to define arrays. For this purpose, we use the command introduced in the previous notebook (`numpy_part1.ipynb`).

In [1]:
import numpy as np

There is the subclass `linalg` in `numpy` which provides the tools required for linear algebra. To import `linalg` in a Python script, we have two options:

* Option 1: Import `linalg` as a whole. Then in the script, we can call specific methods (functions) from `linalg`. 
* Option 2: Import the methods needed in the script from `numpy.linalg`. 

Both of these are used in practice, and you can decide which one to use. But within the present notebook, we adopt the first option. 

In [2]:
# Option 1: import the whole linalg
import numpy.linalg as la

In [3]:
# Option 2: Import a specific method from linalg
from numpy.linalg import norm

## 2. Norm of arrays
From mathematical point of view, there are different types of norms which can be applied to an array. Let us be more specific and focus only on the 1D and 2D arrays.

1D arrays:
$$
\mathbf{a} = [a_1,a_2,\cdots,a_n]\,,\quad \mathbf{a}=[a_i]\,,\quad  \text{where}\,\, i=1,2,\cdots,n
$$


Some most frequently-used norms for the vectors are given bellow:

* $L_1$ norm: sum of the absolute values of elements
$$
\|\mathbf{a}\|_1 = \sum_{i=1}^n |a_i|
$$

* $L_2$ norm: square root of the sum of squares of elements

$$
\|\mathbf{a}\|_2 = \left (\sum_{i=1}^n a^2_i \right)^{1/2}
$$

* $L_\infty$ norm: maximum absolute value of the elements

$$
\|\mathbf{a}\|_\infty = \max_{1\leq i\leq n} |a_i|
$$

Consider a general $m\times n$ matrix $\mathbf{A}$:

$$
\mathbf{A} = 
\begin{bmatrix}
A_{11} & A_{12} & \cdots & A_{1n} \\
A_{21} & A_{22} & \cdots & A_{2n} \\
\vdots & \ddots & \cdots & \vdots \\
A_{m1} & A_{m2} & \cdots & A_{mn} \\
\end{bmatrix}
\,,\quad \mathbf{A}=[A_{ij}] \,\, \text{where} \,\, i=1,2,\cdots,m \,,\, j=1,2,\cdots,n
$$

For this matrix, the above norms are defined as:

* $L_1$ norm: maximum column-sum of the absolute values of elements:
$$
\|\mathbf{A}\|_1 = \max_{1\leq j\leq n}\sum_{i=1}^m |A_{ij}|
$$

* $L_2$ norm: square root of the maximum eigenvalue of $\mathbf{A^*} \mathbf{A}$ where $A^*$ is the conjugate transpose of $\mathbf{A}$:
$$
\|\mathbf{A}\|_2 = \sqrt{\lambda_{\max} (\mathbf{A}^*\mathbf{A})}
$$


* $L_\infty$ norm: maximum row-sum of the absolute values of elements:
$$
\|\mathbf{A}\|_\infty = \max_{1\leq i\leq m}\sum_{j=1}^n |A_{ij}|
$$




To find the norm of an array in `numpy`, we use `numpy.linalg.norm(a,s)` where `s` can be 1, 2, or `numpy.inf` to get the $L_1$, $L_2$, and $L_\infty$ norm of the array, respectively. Note that the syntax is the same for matrices of any shape. 

Example: 1D array

In [4]:
a = np.array([-1,3,4,5])

print('L1-norm of a:',la.norm(a,1))
print('L2-norm of a:',la.norm(a,2))
print('Linf-norm of a:',la.norm(a,np.inf))

L1-norm of a: 13.0
L2-norm of a: 7.14142842854285
Linf-norm of a: 5.0


Example: 2D array

In [5]:
A = np.array([[-1,3,4],[2,3,6]])

print(A)
print('L1-norm of A:',la.norm(A,1))
print('L2-norm of A:',la.norm(A,2))
print('Linf-norm of A:',la.norm(A,np.inf))

[[-1  3  4]
 [ 2  3  6]]
L1-norm of A: 10.0
L2-norm of A: 8.400257807634889
Linf-norm of A: 11.0


## 3. Determinant of a square matrix

To find the determinant of a square matrix using `numpy.linalg`, we need `det(B)`:

In [6]:
B = np.array([[-1,3,4],[2,3,6],[6,-9,0]])

print(B)
print('det(B)=',la.det(B))

[[-1  3  4]
 [ 2  3  6]
 [ 6 -9  0]]
det(B)= -90.0


## 4. Inverse of a square matrix

To find the inverse of a square matrix using `numpy.linalg`, we need `inv(B)`:

In [7]:
B_inv = la.inv(B)
print('inv(B)=',B_inv)

inv(B)= [[-0.6         0.4        -0.06666667]
 [-0.4         0.26666667 -0.15555556]
 [ 0.4        -0.1         0.1       ]]


We can check if $\mathbf{B}  \mathbf{B}^{-1} = \mathbf{I}$, where $\mathbf{I}$ is the identity matrix of the same size as $\mathbf{B}$:

In [8]:
print(B @ B_inv)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  5.55111512e-17]
 [ 1.66533454e-16 -5.55111512e-17  1.00000000e+00]]


## 5. Decompositions

A given matrix can be decomposed in various ways. Below, we provide the `numpy.linalg` commands for those decompositions which are needed within the course. 

### 5.1. Cholesky decomposition

Assume $\mathbf{C}$ is a Hermitian positive definite square matrix. If all elements are real, then $\mathbf{C}$ is a symmetric positive definite matrix. This is the case that we deal within the course. <br>

By Cholesky decomposition, $\mathbf{C}$ is decomposed into a lower-triangular matrix $\mathbf{L}$ and its transpose:

$$
\mathbf{C} = \mathbf{L}\mathbf{L}^T
$$

In [9]:
C = np.array([[4,-12,16],[12,37,-43],[-16,-43,98]])
print(C)

[[  4 -12  16]
 [ 12  37 -43]
 [-16 -43  98]]


In `numpy`, we use `L = cholesky(C)`:

In [10]:
L = la.cholesky(C)  #returns lower triangular matrix
print(L)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


We can check if $\mathbf{C} = \mathbf{L}\mathbf{L}^T$ holds numerically:

In [11]:
C2 = L @ L.T

In [12]:
print('C-L*L.T = ',C-C2)

C-L*L.T =  [[  0. -24.  32.]
 [  0.   0.   0.]
 [  0.   0.   0.]]


### 5.2. QR decomposition

Assume $\mathbf{E}$ is a real square matrix. Then it can be decompose as, 

$$
\mathbf{E} = \mathbf{Q}\mathbf{R}
$$

where, 

* $\mathbf{Q}$ is an orthogonal matrix, i.e. $\mathbf{Q}^T = \mathbf{Q}^{-1}$. 
* $\mathbf{R}$ is an upper triangular matrix. 

In `numpy.linalg` we use `Q,R = qr(E)`:

In [13]:
E = np.array([[3,-5,6],[9,4,7],[-2,5,-1]])
print(E)

[[ 3 -5  6]
 [ 9  4  7]
 [-2  5 -1]]


In [14]:
Q,R = la.qr(E)
print('Q=', Q)
print('R=',R)

Q= [[-0.30942637  0.66518914  0.67954303]
 [-0.92827912 -0.36631688 -0.06410783]
 [ 0.20628425 -0.65064226  0.73082929]]
R= [[-9.69535971 -1.13456337 -8.56079634]
 [ 0.         -8.04442453  2.07755892]
 [ 0.          0.          2.89767405]]


Now, let's check if the orthogonality of $\mathbf{Q}$ holds numerically:

In [15]:
Q_inv = la.inv(Q)
Q_t = Q.T
print('inv(Q)-Q.T = ',Q_inv-Q_t)

inv(Q)-Q.T =  [[-2.22044605e-16 -2.22044605e-16 -5.55111512e-17]
 [-3.33066907e-16  2.22044605e-16  3.33066907e-16]
 [ 0.00000000e+00  1.52655666e-16  1.11022302e-16]]


## 6. Eigen decomposition of matrices

Consider a square matrix $\mathbf{A}$. Then the eigen decomposition of $\mathbf{A}$ is:

$$
\mathbf{A} \mathbf{v} = \lambda \mathbf{v}
$$
where $\lambda$ is an eigenvalue of $\mathbf{A}$ and $\mathbf{v}$ is its corresponding eigenvector. 

For an $n\times n$ matrix $\mathbf{A}$, we have $n$ eigenvalues and corresponding eigenvectors. All these $n$ eigen pairs can be obtained at once in `numpy.linalg` by running `eigVals,eigVecs = eig(A)`. 

Note that, 
* `eigVals` is a 1D array of size $n$ containing the eigenvalues of $\mathbf{A}$, 
* `eigvecs` is a $n\times n$  matrix, the $i$-th column of which is the eigenvector corresponding to the $i$-th eigenvalue. 

In [16]:
A = np.array([[3,8,6],[9,4,7],[-2,5,-1]])

In [17]:
eigVals,eigVecs = la.eig(A)

In [18]:
print('Eigenvalues:',eigVals)

Eigenvalues: [-5.27528315 -2.25556381 13.53084696]


In [19]:
print(eigVecs)

[[ 0.05638467 -0.39661523  0.65427134]
 [-0.63571886 -0.36964896  0.73826754]
 [ 0.76985863  0.84027139  0.16398184]]


Let's check if the $L_2$ norm of the eigenvectors is unity. Simply, we compute the norm of the columns of `eigVecs`:

In [20]:
for i in range(A.shape[0]):
    print('Norm of eigenvector %i = %g' %(i+1,la.norm(eigVecs[:,i],2)))

Norm of eigenvector 1 = 1
Norm of eigenvector 2 = 1
Norm of eigenvector 3 = 1


## 7. Direct solution of a linear system of equations

Consider the linear system ,
$$
\mathbf{A} \mathbf{x} = \mathbf{f} \,,
$$
where,
* $\mathbf{A}$ is an $n\times n$ matrix (coefficient matrix), 
* $\mathbf{n}$ is an $n\times 1$ matrix (solution vector/matrix),
* $\mathbf{f}$ is an $n\times 1$ matrix (right-hand-side vector/matrix). 

If the matrix $\mathbf{A}$ is invertible, i.e. $\mathbf{A}^{-1}$ exists, then the above linear system can be directly solved as, 
$$
\mathbf{x} = \mathbf{A}^{-1}\mathbf{f} \,.
$$
This is called the direct solution of a linear system. In contrast, we have the iterative methods that will be discussed thoroughly along with their Python implementations during the course. 

Calling a method in `numpy.linalg` for directly solving a linear system is as simple as: `x = solve(A,f)`.

In [21]:
A = np.asarray([[4,2,0,0],
              [2,3,1,0],
              [0,-1,2,0.5],
              [0,0,1,5]])

f = np.array([21,69,34,22])

Let's solve the system $\mathbf{A} \mathbf{x} = \mathbf{f}$ numerically:

In [22]:
x = la.solve(A,f)

In [23]:
print('solution x = ',x)
print('shape of x:', x.shape)

solution x =  [-3.015625 16.53125  25.4375   -0.6875  ]
shape of x: (4,)


Note that instead of using the built-in function `solve`, we could directly compute $\mathbf{x}$ from $\mathbf{x} = \mathbf{A}^{-1}\mathbf{f}$:

In [24]:
x2 = la.inv(A) @ f

In [25]:
print(x2)

[-3.015625 16.53125  25.4375   -0.6875  ]
