# A crash course on `numpy` - Part I

Saleh Rezaeiravesh, saleh.rezaeiravesh@manchester.ac.uk <br>
Department of Fluids and Environment, The University of Manchester, Manchester, UK
___

This is a short introduction to `numpy`, a package (library) for scientific computing in Python. Here we cover some basic things that are required for the Numerical Methods & Computing course. For more detailed instructions and examples, refer to the official [numpy page](https://numpy.org/doc/stable/user/absolute_beginners.html). 

### Intended Learning Outcomes:
By reading and running this notebook, the students should be able to:
* Import the `numpy` and its methods. 
* Use `numpy` to define arrays and implement different operations relevant to them. 

## 1. Import `numpy`
At the beginning of any `.py` script, we should import `numpy` to have access to different classes, functions, and attributes within it. The imported library can be named by anything, here `np`.

In [1]:
import numpy as np

## 2. Define an array
Within this course, we only consider the arrays of numbers. The mathematical correspondence to these arrays are tensors. As we know, a zero-order tensor is scalar, a first-order tensor is a vector, and higher-order tensors are usually referred to as matrices. In the following cells, we provide a few examples for defining arrays in `numpy`. For this purpose we use `numpy.array([....])`.

### 2.1 1D Arrays (vectors)
Let's define $\mathbf{x}_1=[-1,3,5,7]$ that is a vector of size 4:

In [2]:
x1=np.array([-1,3,5,7])

Print the array:

In [3]:
print(x1)

[-1  3  5  7]


For any array defined in `numpy`, we can get the dimension, size, and shape of the array using the following attributes:

* **Dimension**: `ndim`
* **Size**: `size`
* **Shape**: `shape`

Let's apply this to `x1` array defined above:

In [4]:
print('dimension:',x1.ndim)
print('shape:',x1.shape)
print('size:',x1.size)

dimension: 1
shape: (4,)
size: 4


**Note:** In contrast to Matlab, a 1D array in Python has the shape, here, `(4,)` and not `(4,1)`. <br>

To reshape `x1` to the latter that is a 2D array (matrix), we can do the following:

In [5]:
x2 = x1[:,None]

print(x2)
print('dimension:',x2.ndim)
print('shape:',x2.shape)
print('size:',x2.size)

[[-1]
 [ 3]
 [ 5]
 [ 7]]
dimension: 2
shape: (4, 1)
size: 4


Note that now, each element of the array is within the brackets. 

### 2.2 2D Arrays (2D Matrices)
We are familiar with 2D arrays or matrices that can be square or non-square, for instance:

$$
\mathbf{A}_1 = 
\begin{bmatrix}
   -1 & 3 & 4 \\
   2 & -5 &7 \\
\end{bmatrix}
\,,
\quad\quad
\mathbf{A}_2 = 
\begin{bmatrix}
   -1 & 3 & 4 \\
   2 & -5 &7 \\
   0 & 6 & 8\\
\end{bmatrix}
$$
Again we use `numpy.array` to define these in Python. 

In [6]:
A1 = np.array([[-1,3,4], [2,-5,7]])
A2 = np.array([[-1,3,4], [2,-5,7], [0,6,8]])

Clearly, every row of the mathematical matrices are defined within the internal square brackets separated by a comma. The outermost brackets are specifying the whole matrix. <br>

We can print these arrays along with their dimension, size, and shape:

In [7]:
print(A1)
print('dimension, size, shape of A1: ',A1.ndim,A1.size,A1.shape)

[[-1  3  4]
 [ 2 -5  7]]
dimension, size, shape of A1:  2 6 (2, 3)


In [8]:
print(A2)
print('dimension, size, shape of A2: ',A2.ndim,A2.size,A2.shape)

[[-1  3  4]
 [ 2 -5  7]
 [ 0  6  8]]
dimension, size, shape of A2:  2 9 (3, 3)


These show that, 
* `A1` is a 2D array (matrix) of shape $2\times 3$ with $6$ elements, in total. 
* `A2` is a 2D array (matrix) of shape $3\times 3$ with $9$ elements, in total. 

**Note:** Clearly, the shape of an array is also an array:

In [9]:
A1_shape = A1.shape
print(A1_shape)
print(A1_shape[0],A1_shape[1])

(2, 3)
2 3


### 2.3 Initialising Arrays

In some cases in Python codes, we need to define arrays of known sizes. For this, we use commands `zeros` and `ones` similar to Matlab, which lead to arrays with all elements equal to 0 and 1, respectively. Clearly, we can premultiply an array defined by `ones` by a scalar to have elements equal to that scalar. 

Define 1D arrays:

In [10]:
y1 = np.zeros(5)
print(y1)

[0. 0. 0. 0. 0.]


In [11]:
y2 = 3.2 * np.ones(6)
print(y2)

[3.2 3.2 3.2 3.2 3.2 3.2]


Define a 2D array: For instance, for an array of shape $4\times 3$, we have

In [12]:
B1=np.zeros((4,3))
print(B1)
print(B1.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)


### 2.4 Convert a list to a `numpy` array

If we a have list of numbers, we can convert it to a `numpy` array of a desired shape. The conversion of a list to a 1D array is achieved through command `asarray`:

In [13]:
l = [1,2,6,-8,3,0]   # a list
la = np.asarray(l)   #conversion to numpy array
print('list:',l)
print('array:',la)
print('array shape:',la.shape)

list: [1, 2, 6, -8, 3, 0]
array: [ 1  2  6 -8  3  0]
array shape: (6,)


Note that contrary to the array, the list does NOTE have a `shape` (among other attributes).

### 2.5 Reshape an array
We can reshape a `numpy` array using `reshape`. Consider a 1D array `x3` of size 6. 

In [14]:
x3 = np.asarray([0,5,-7,8,10,12])

We can convert `x3` to a 2D array of shape $2 \times 3$ or $3 \times 2$:

In [15]:
x4 = np.reshape(x3,(2,3))
print(x4)
print(x4.shape)

[[ 0  5 -7]
 [ 8 10 12]]
(2, 3)


In [16]:
x5 = np.reshape(x3,(3,2))
print(x5)
print(x5.shape)

[[ 0  5]
 [-7  8]
 [10 12]]
(3, 2)


### 2.6 Identity matrix
For an identity matrix, all elements are zero except the diagonal ones that are 1. An identity matrix of size $n$ in `numpy` can be defined by `I = numpy.identity(n)`. For instance, if $n=4$, we have:

In [17]:
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 3. Indices and Slices


### 3.1 Indices
In contrast to Matlab, the indices in lists and `numpy` arrays in Python start from 0. Therefore, for an array of size $n$, the indices range from 0 to $n-1$. These are called positive indexing. In contrast, we can have negative indexing: -1 (corresponding to $n-1$), -2 (corresponding to $n-2$), etc. Note that -1 is the same as `end` in Matlab. <br>
We can get the value of a specific element of an array by calling the array at the associated index. 

**1D Arrays:**

<img src=static/index1d.png alt="Alternative text" width='400' height="400" />

In [18]:
print(x1)   
print('Shape of x1:',x1.shape)
print('1st element of x1:',x1[0])
print('2nd element of x1:',x1[3])
print('Last element of x1:',x1[-1])
print('Second last element of x1:',x1[-2])

[-1  3  5  7]
Shape of x1: (4,)
1st element of x1: -1
2nd element of x1: 7
Last element of x1: 7
Second last element of x1: 5


**2D Arrays**: <br>
Combining the positive and negative indexing for the rows and columns, we have various ways of referring to the same element in the multidimensional arrays.

<img src=static/index2d.png alt="Alternative text" width='500' height="500" />

In [19]:
print(A1)
print('Shape of A1:',A1.shape)
print('Element A1[0,2]=',A1[0,2])
print('Element A1[-2,2]=',A1[-2,2])
print('Element A1[-2,-1]=',A1[-2,-1])
print('Element A1[0,-1]=',A1[0,-1])

[[-1  3  4]
 [ 2 -5  7]]
Shape of A1: (2, 3)
Element A1[0,2]= 4
Element A1[-2,2]= 4
Element A1[-2,-1]= 4
Element A1[0,-1]= 4


 ### 3.2 Slicing 

Sometimes we need slices of data stored in an array. The slicing is applied by selecting a subrange of indices in different dimensions of an array.

**1d Arrays**:

<img src=static/slicing1d.png alt="Alternative text" width='400' height="400" />

In [20]:
print('original array',x1)

original array [-1  3  5  7]


In [21]:
print(x1[1:])

[3 5 7]


In [22]:
print(x1[:2])
print(x1[:-2])

[-1  3]
[-1  3]


In [23]:
print(x1[1:3])
print(x1[-3:-1])

[3 5]
[3 5]


**2D Arrays:**

In [24]:
print(A1)

[[-1  3  4]
 [ 2 -5  7]]


In [25]:
print(A1[1:2,:-1])
print(A1[1:2,:-1].shape)

[[ 2 -5]]
(1, 2)


In [26]:
print(A1[1:2,:-2])
print(A1[1:2,:-2].shape)

[[2]]
(1, 1)


## 4. Basic array operations

`numpy` provides a wide range of operations applied to arrays. This brings a great flexibility and computational efficiency when working with arrays. Moreover, the scripts developed for different numerical algorithms have a very high readability and abstraction. In the following lines, we cover the most essential operations in `numpy`. 

### 4.1 Addition and subtraction

As we know to add or subtract two or more matrices, the shape (dimension and size) of the matrices must be the same. Keeping this in mind, we can simply use `+` and `-` signs for addition and subtraction of `numpy` arrays, respectively.

**1D Arrays**

Consider two vectors $a_1$ and $a_2$:

$$
a_1=[-1,3,4,5]\,,\quad\quad
a_2=[5,-1,2,8]
$$

For addition and subtraction of these two vectors in `numpy`, we have:

In [27]:
a1=np.array([-1,3,4,5])
a2=np.array([5,-1,2,8])
s=a1+a2
d=a1-a2
print('a1+a2=',s)
print('a1-a2=',d)

a1+a2= [ 4  2  6 13]
a1-a2= [-6  4  2 -3]


The results are vectors with the same shape as `a1` and `a2`.

**2D Arrays**: <br>
The same holds for multidimensional arrays. For instance, consider $B_1$ and $B_2$ that are both $2\times 3$ matrices:
$$
B_1=
\begin{bmatrix}
-1 & 3 & 4 \\
2 & 3 & 6\\
\end{bmatrix}
\,,\quad\quad
B_2=
\begin{bmatrix}
2 & -5 & 1 \\
12 & 2 & 4\\
\end{bmatrix}
$$
The elementwise addition and subtraction of these two arrays are done by `B1+B2` and `B1-B2`, respectively. 

In [28]:
B1 = np.array([[-1,3,4],[2,3,6]])
B2 = np.array([[2,-5,1],[12,2,4]])
S1 = B1+B2
D1 = B1-B2

In [29]:
print('B1+B2=',S1)
print('B1-B2=',D1)

B1+B2= [[ 1 -2  5]
 [14  5 10]]
B1-B2= [[ -3   8   3]
 [-10   1   2]]


## 4.2 Matrix transpose
A transpose of a matrix is obtained by switching its rows and columns. To find the transpose of an array `A` in `numpy`, we can use either of the following commands:
 
 * `A.T`
 * `numpy.transpose(A)`

For instance, for the $2\times 3$ array $B_1$ defined as

$$
B_1=
\begin{bmatrix}
-1 & 3 & 4 \\
2 & 3 & 6\\
\end{bmatrix}
$$
we should get 
$$
B_1^T=
\begin{bmatrix}
-1 & 2\\
3 & 3\\
4 & 6\\
\end{bmatrix}
$$

In [30]:
print('B1 = ',B1)
print('B1^T = ',B1.T)
print('B1^T = ',np.transpose(B1))

B1 =  [[-1  3  4]
 [ 2  3  6]]
B1^T =  [[-1  2]
 [ 3  3]
 [ 4  6]]
B1^T =  [[-1  2]
 [ 3  3]
 [ 4  6]]


Clearly, the transposed matrix has the size $3\times 2$:

In [31]:
print('B1 shape:',B1.shape)
print('B1.T shape:',B1.T.shape)

B1 shape: (2, 3)
B1.T shape: (3, 2)


**Note:** The transpose of a `numpy` array is not meaningful for the vectors which are one-dimensional arrays. In case you want to convert a row vector to a column one, or vice versa, you should first make the vector two-dimensional and then transpose. <br>

Let's consider `a1` that is a vector:

In [32]:
print('a1 as a vector:')
print(a1,a1.shape)

a1 as a vector:
[-1  3  4  5] (4,)


First, we make it two dimensional (the result is a column matrix):

In [33]:
print('a1 as a column matrix:')
aa1 = a1[:,None]
print(aa1)
print(aa1.shape)

a1 as a column matrix:
[[-1]
 [ 3]
 [ 4]
 [ 5]]
(4, 1)


Now, the transpose can be applied:

In [34]:
print('a1 as a row matrix:')
aa1T = aa1.T
print(aa1T)
print(aa1T.shape)

a1 as a row matrix:
[[-1  3  4  5]]
(1, 4)


## 5. Multiplication of arrays


### 5.1. General operator
For multiplication of arrays in `numpy`, we use the operator `@`. But, we must be careful about checking the shape of arrays which are going to be multiplied to make sure the operation is mathematically possible (i.e. there is no mismatch between the relevant sizes). This means, for instance, if $\mathbf{A}$ is $2\times 3$ and $\mathbf{B}$ is $3\times 4$, then only $\mathbf{AB}$ can be done, and not $\mathbf{BA}$. 

Example: matrix-matrix multiplication

In [35]:
A = np.array([[2,-5,1],[12,2,4]])
B = np.array([[4,2,-7,11],[-2,2,6,0],[19,-3,-8,4]])
print('Shape of A:',A.shape)
print('Shape of B:',B.shape)

Shape of A: (2, 3)
Shape of B: (3, 4)


Let's find $\mathbf{AB}$:

In [36]:
C = A @ B
print(C)
print('Shape of AB,',C.shape)

[[  37   -9  -52   26]
 [ 120   16 -104  148]]
Shape of AB, (2, 4)


If we try $\mathbf{BA}$, an error message will appear saying there is a "mismatch in the dimensions":

In [37]:
print(B@A)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

**Note**: The operator `@` is a shorthand for `numpy.matmul(...)`. Their results are the same. 

In [38]:
C2=np.matmul(A,B)
print(C2)

[[  37   -9  -52   26]
 [ 120   16 -104  148]]


Example: Matrix vector multiplication. <br>
    
Consider $\mathbf{A}$ is a $2\times 3$ matrix, and $b$ is a vector of size $3$. For implementing the multiplication $\mathbf{Ab}$ in `numpy`, `A@b` works for `b` being either a $3\times 1$ column vector of just a 1D array of size $3$. For these two cases, the resulting $A@b$ has the shape $2\times 1$ and $2$, respectively. 

In [39]:
A = np.array([[2,-5,1],[12,2,4]])
b = np.array([-4,7,1])  #1D array
print('Shape of A:',A.shape)
print('Shape of b:',b.shape)
print(A@b)
print('Ab shape:',(A@b).shape)

Shape of A: (2, 3)
Shape of b: (3,)
[-42 -30]
Ab shape: (2,)


In [40]:
b = np.array([-4,7,1])[:,None]  #2D array 3 x1
print('Shape of A:',A.shape)
print('Shape of b:',b.shape)
print(A@b)
print('Ab shape:',(A@b).shape)

Shape of A: (2, 3)
Shape of b: (3, 1)
[[-42]
 [-30]]
Ab shape: (2, 1)


## 5.2. Inner (dot) product

In many cases, we would like to have an inner or dot product of arrays. But, we should note that:

* For 1D arrays (vectors) $\mathbf{a}$ and $\mathbf{b}$ of equal length, `numpy.dot(a,b)` is a scalar (exactly like the mathematical dot product). A similar result can be obtained from `a@b` (See Example 1 below).
* For higher-dimensional matrices $\mathbf{A}$ and $\mathbf{B}$, `numpy.dot(A,B)` is identical to `A@B` (see Example 2 below).

Example 1: dot product of two vectors

In [41]:
a=np.array([1,2,4])
b=np.array([4,2,7])
c=np.dot(a,b)
print('shape of a and b:',a.shape,b.shape)
print('dot(a,b) =',c)
print('a@b =',a@b)

shape of a and b: (3,) (3,)
dot(a,b) = 36
a@b = 36


Example 2: dot product of two 2D arrays

In [42]:
A = np.array([[2,-5,1],[12,2,4]])
B = np.array([[4,2,-7,11],[-2,2,6,0],[19,-3,-8,4]])
print('Shape of A:',A.shape)
print('Shape of B:',B.shape)

C1=np.dot(A,B)   #for multi-dim arrays, dot acts the same as @
print(C1)
print('Shape of dot(A,B)',C1.shape)
print('A@B',A@B)

Shape of A: (2, 3)
Shape of B: (3, 4)
[[  37   -9  -52   26]
 [ 120   16 -104  148]]
Shape of dot(A,B) (2, 4)
A@B [[  37   -9  -52   26]
 [ 120   16 -104  148]]


### 6. Minimum, maximum, and summation

* `numpy.max(A)`: returns the element of `A` with maximum value
* `numpy.max(A)`: returns the element of `A` with minimum value
* `numpy.sum(A)`: returns the sum of elements of `A`

`A` can be an array of any dimension.

In [43]:
print(a)
print('min(a)=',np.min(a))
print('max(a)=',np.max(a))
print('sum(a)=',np.sum(a))

[1 2 4]
min(a)= 1
max(a)= 4
sum(a)= 7


In [44]:
print(A)
print('min(A)=',np.min(A))
print('max(A)=',np.max(A))
print('sum(A)=',np.sum(A))

[[ 2 -5  1]
 [12  2  4]]
min(A)= -5
max(A)= 12
sum(A)= 16


### 5.3. Scalar-array operations
We can simply multiply or divide a `numpy` array of any shape by a scalar using `*` and `/`, respectivelt. By these, all elements of the array are multiplied/divided by the scalar. The shape of the resulting array is the same as the original one. y

In [45]:
print('a:',a)
print('5*a:', 5*a)
print('a/2.3:', a/2.3)

a: [1 2 4]
5*a: [ 5 10 20]
a/2.3: [0.43478261 0.86956522 1.73913043]


In [46]:
print('A:',A)
print('5*A:', 5*A)
print('A/2.3:', A/2.3)

A: [[ 2 -5  1]
 [12  2  4]]
5*A: [[ 10 -25   5]
 [ 60  10  20]]
A/2.3: [[ 0.86956522 -2.17391304  0.43478261]
 [ 5.2173913   0.86956522  1.73913043]]


**Note**: Note that, in contrast to Matlab, we do not need to use `.*` or `./` for the above operations. 

We can combine different operations applied to the arrays. 
For instance, Consider $\mathbf{A}$ and $\mathbf{B}$ are two `3\times 2` arrays. We can implement the mathematical expression 
$$\mathbf{C}=(4.3\mathbf{A}+\mathbf{B}/3)\mathbf{A}^T$$
in `numpy` as simple as `C=(4.3*A+B/3)@A.T`. <br>
This shows how high-level, prctical and nice `numpy` is :)

In [47]:
A = np.array([[2,-5,1],[12,2,4]])
B = np.array([[-12,4,-1],[6,8,-7]])

In [48]:
C = (4.3*A + B/3) @ A.T

In [49]:
print(C)
print(C.shape)

[[114.          30.73333333]
 [ 65.73333333 725.2       ]]
(2, 2)
